### ISSUE TITLE
Please Example to use this package

### ISSUE THREAD

**Issue by Jayuda** [jshimko/meteor-selectize#5]
Hello Guys,
please help me to give me example code that use this package.
Thanks you

**Comment by jshimko** [comment]
This package is just the Selectize library with no modifications for Meteor, so all of the [examples][1] in the main project repo are done exactly the same way in Meteor.  You can open any one of those HTML files and see the HTML and javascript for every example.  I recommend downloading the whole folder so you can open those files in your browser too.

[1]: https://github.com/brianreavis/selectize.js/tree/master/examples

**Comment by Jayuda** [comment]
Thanks

**Comment by allenfuller** [comment]
One note regarding use in Meteor is that if you use dynamic options from the server, and add them to the select via a helper, Selectize will not detect them because they don't exist in the template when it is initialized.

The only workaround I found was to add a `Meteor.setTimeout();` wrapper around Selectize. This waits to render Selectize until the helper has had time to load.

I'm only adding it here because I've spent a few hours trying to solve this problem and just wanted to help someone else avoid that pain. :)

**Comment by jshimko** [comment]
@allenfuller, have you tried using something like `refreshOptions()` from the Selectize API?

https://github.com/selectize/selectize.js/blob/master/docs/api.md#methods_options

You could use that with an autorun that watches for your data to be ready.  If `subs.ready()`, then `refreshOptions()`.  (or whatever that looks like)
